# Generated by Django 4.1.5 on 2023-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item_name',
            new_name='item',
        ),
    ]
